### ISSUE TITLE
gnuplot checking and gnuplot window size 

### ISSUE THREAD

**Issue by holgafreak** [vsergeev/luaradio#43]
I use torch7 a lot, and use luajit from torch. Checking if gnuplot is installed fails with torch luajit, because assertion 
```
  -- Check gnuplot exists
    assert(os.execute("gnuplot --version >/dev/null 2>&1") == 0, "gnuplot not found. Is gnuplot installed?")
```
fails, because os.execute return true instead of 0. Changing 0 to true makes luaradio happy. This with my luajit 
xxx-GL553VW:~$ luajit -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

Also trying to change the gnuplot window size something goes wrong and gnuplot dies. The gnuplot window is little bit too big. When some examples plot 3 windows, they all don't fit on my laptop monitor without overlapping windows flickering annoyingly. Dragging windows to smaller is ok.
I'm on Ubuntu 16.04:
uname -a
Linux xxxx-GL553VW 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vsergeev** [comment]
Thanks. I've fixed the gnuplot existence checks in master. They're due to LuaJIT being built with `-DLUAJIT_ENABLE_LUA52COMPAT`, which uses the Lua 5.2 API for `os.execute()`. The Lua 5.2 `os.execute()` returns more detailed status information (beginning with a success boolean) instead of just an exit code.

As for the gnuplot issues, there are stability issues in general (#26), especially when doing something like resizing. I recommend using the wxWidgets output if you haven't tried it already. It seems to be the most reliable for me.
