### ISSUE TITLE
[Install] Update homebrew package with v0.6.0

### ISSUE THREAD

**Issue by vsergeev** [vsergeev/luaradio#54]
I currently don't have access to a Mac for development to update the package, but I'm looking into running a VM.

**Comment by umi-neko** [comment]
Hi,
Glad to see luaradio release new version.
I am using brew install luaradio, but it still try to install v0.5.1 for me. Do I need to add some tap for v0.6.0?

**Comment by vsergeev** [comment]
LuaRadio is in homebrew/core, but the package just needs to be updated for v0.6.0. I just don't currently have access to a Mac / VM to make the update, test it, and submit a PR to homebrew.

**Comment by BG7JAF** [comment]
Hello,
I clone the git source and try to run the FM example code on macOS 10.15.2, but it can't work. Seems it's incompatible with pulseaudio which version is 13.0 (installed from brew).
Here is the error messages:

➜  luaradio git:(master) ✗ ./luaradio fm.lua
Found Rafael Micro R820T tuner
Exact sample rate is: 1102500.002464 Hz
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[PulseAudioSink] Block runtime error: ./radio/blocks/sinks/pulseaudio.lua:108: pa_simple_new(): Connection refused
stack traceback:
	[C]: in function 'error'
	./radio/blocks/sinks/pulseaudio.lua:108: in function 'initialize_pulseaudio'
	./radio/blocks/sinks/pulseaudio.lua:119: in function 'process'
	./radio/core/block.lua:399: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[DownsamplerBlock] Downstream block PulseAudioSink terminated unexpectedly.
[DownsamplerBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[FMDeemphasisFilterBlock] Downstream block DownsamplerBlock terminated unexpectedly.
[FMDeemphasisFilterBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[LowpassFilterBlock] Downstream block FMDeemphasisFilterBlock terminated unexpectedly.
[LowpassFilterBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[FrequencyDiscriminatorBlock] Downstream block LowpassFilterBlock terminated unexpectedly.
[FrequencyDiscriminatorBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[DownsamplerBlock] Downstream block FrequencyDiscriminatorBlock terminated unexpectedly.
[DownsamplerBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[LowpassFilterBlock] Downstream block DownsamplerBlock terminated unexpectedly.
[LowpassFilterBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[FrequencyTranslatorBlock] Downstream block LowpassFilterBlock terminated unexpectedly.
[FrequencyTranslatorBlock] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/core/block.lua:404: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300
[RtlSdrSource] Downstream block FrequencyTranslatorBlock terminated unexpectedly.
[RtlSdrSource] Block runtime error: ./radio/core/pipe.lua:310: write(): Broken pipe
stack traceback:
	[C]: in function 'error'
	./radio/core/pipe.lua:310: in function 'write'
	./radio/blocks/sources/rtlsdr.lua:231: in function <./radio/blocks/sources/rtlsdr.lua:219>
	[C]: in function 'rtlsdr_read_async'
	./radio/blocks/sources/rtlsdr.lua:249: in function 'run'
	./radio/core/composite.lua:539: in function <./radio/core/composite.lua:539>
	[C]: in function 'xpcall'
	./radio/core/composite.lua:539: in function 'start'
	./radio/core/composite.lua:432: in function 'run'
	fm.lua:11: in main chunk
	[C]: in function 'dofile'
	./luaradio:110: in main chunk
	[C]: at 0x010b86c300

**Comment by vsergeev** [comment]
@BG7JAF, is the PulseAudio server running? You may need to start it with `brew services start pulseaudio`.

**Comment by umi-neko** [comment]
@vsergeev it's the reason!  After follow your instruction start the pulseaudio service, it can work now. I will do other test. Thankyou

**Comment by vsergeev** [comment]
Resolved with homebrew/homebrew-core#49807
